# This file holds all of the standard configuration for our development environment

version: '3.7'

services:
    #External Services

    mongodb:
        image: mongo
        ports: 
            - "27017:27017"

    # External Clients
    mongodb-dashboard:
        image: mongo-express
        ports:
            - "8081:8081"
        environment: 
            - ME_CONFIG_MONGODB_SERVER=mongodb
        restart: on-failure
        
